#include "vb/cli/service.hpp"

namespace vb::cli {

namespace {

std::string xml_escape(const std::string &s) {
	std::string out;
	for (const char c : s) {
		switch (c) {
			case '&':
				out += "&amp;";
				break;
			case '<':
				out += "&lt;";
				break;
			case '>':
				out += "&gt;";
				break;
			case '"':
				out += "&quot;";
				break;
			case '\'':
				out += "&apos;";
				break;
			default:
				out += c;
				break;
		}
	}
	return out;
}

// systemd splits ExecStart on whitespace and expands %-specifiers and $VARS, so
// every word is double-quoted with \ " % and $ made literal.
std::string systemd_word(const std::string &s) {
	std::string out = "\"";
	for (const char c : s) {
		switch (c) {
			case '\\':
				out += "\\\\";
				break;
			case '"':
				out += "\\\"";
				break;
			case '%':
				out += "%%";
				break;
			case '$':
				out += "$$";
				break;
			default:
				out += c;
				break;
		}
	}
	return out + "\"";
}

std::string label(const std::string &name) { return "com.voxelbrowser.server." + name; }

std::string systemd_unit(const ServiceSpec &s) {
	std::string out;
	out += "# Voxel Browser server '" + s.name + "' -- generated by `vb server service print`.\n";
	out += "[Unit]\nDescription=Voxel Browser server '" + s.name + "'\nAfter=network-online.target\n\n";
	out += "[Service]\nType=simple\n";
	out += "WorkingDirectory=" + systemd_word(s.instance_dir.string()) + "\n";
	if (!s.vb_home.empty()) {
		out += "Environment=" + systemd_word("VB_HOME=" + s.vb_home) + "\n";
	}
	out += "ExecStart=" + systemd_word(s.vb_exe.string()) + " server start " + systemd_word(s.name) +
			" --foreground\n";
	// vb forwards SIGTERM to the server, which saves the world before exiting;
	// "mixed" signals only vb first and waits, instead of TERM-ing both at once.
	out += "KillMode=mixed\nKillSignal=SIGTERM\nTimeoutStopSec=60\n";
	out += "Restart=on-failure\nRestartSec=5\n";
	out += "StandardOutput=append:" + s.log_file.string() + "\n";
	out += "StandardError=append:" + s.log_file.string() + "\n\n";
	out += "[Install]\nWantedBy=default.target\n";
	return out;
}

std::string launchd_plist(const ServiceSpec &s) {
	const auto str = [](const std::string &v) { return "<string>" + xml_escape(v) + "</string>"; };
	std::string out =
			"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
			"<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" "
			"\"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n"
			"<!-- Generated by `vb server service print` (comments cannot contain a double dash). -->\n"
			"<plist version=\"1.0\">\n<dict>\n";
	out += "\t<key>Label</key>\n\t" + str(label(s.name)) + "\n";
	out += "\t<key>ProgramArguments</key>\n\t<array>\n";
	for (const std::string &arg : { s.vb_exe.string(), std::string("server"), std::string("start"),
				 s.name, std::string("--foreground") }) {
		out += "\t\t" + str(arg) + "\n";
	}
	out += "\t</array>\n";
	out += "\t<key>WorkingDirectory</key>\n\t" + str(s.instance_dir.string()) + "\n";
	if (!s.vb_home.empty()) {
		out += "\t<key>EnvironmentVariables</key>\n\t<dict>\n\t\t<key>VB_HOME</key>\n\t\t" +
				str(s.vb_home) + "\n\t</dict>\n";
	}
	out += "\t<key>RunAtLoad</key>\n\t<true/>\n";
	// Restart after a crash, but not after a clean stop (`vb server stop`).
	out += "\t<key>KeepAlive</key>\n\t<dict>\n\t\t<key>SuccessfulExit</key>\n\t\t<false/>\n\t</dict>\n";
	out += "\t<key>ExitTimeOut</key>\n\t<integer>60</integer>\n";
	out += "\t<key>StandardOutPath</key>\n\t" + str(s.log_file.string()) + "\n";
	out += "\t<key>StandardErrorPath</key>\n\t" + str(s.log_file.string()) + "\n";
	out += "</dict>\n</plist>\n";
	return out;
}

std::string task_xml(const ServiceSpec &s) {
	std::string command;
	std::string arguments;
	if (s.vb_home.empty()) {
		command = s.vb_exe.string();
		arguments = "server start " + s.name + " --foreground";
	} else {
		// Scheduled tasks cannot set environment variables; go through cmd.exe.
		command = "cmd.exe";
		arguments = "/c set \"VB_HOME=" + s.vb_home + "\" && \"" + s.vb_exe.string() +
				"\" server start " + s.name + " --foreground";
	}
	std::string out;
	out += "<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n";
	out += "<!-- Generated by `vb server service print`. -->\n";
	out += "<Task version=\"1.4\" xmlns=\"http://schemas.microsoft.com/windows/2004/02/mit/task\">\n";
	out += "  <RegistrationInfo>\n    <Description>Voxel Browser server '" + xml_escape(s.name) +
			"'</Description>\n  </RegistrationInfo>\n";
	out += "  <Triggers>\n    <LogonTrigger>\n      <Enabled>true</Enabled>\n    </LogonTrigger>\n  </Triggers>\n";
	out += "  <Principals>\n    <Principal id=\"Author\">\n      <LogonType>InteractiveToken</LogonType>\n"
		   "      <RunLevel>LeastPrivilege</RunLevel>\n    </Principal>\n  </Principals>\n";
	out += "  <Settings>\n"
		   "    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n"
		   "    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n"
		   "    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n"
		   "    <StartWhenAvailable>true</StartWhenAvailable>\n"
		   "    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>\n"
		   "    <RestartOnFailure>\n      <Interval>PT1M</Interval>\n      <Count>3</Count>\n    </RestartOnFailure>\n"
		   "  </Settings>\n";
	out += "  <Actions Context=\"Author\">\n    <Exec>\n      <Command>" + xml_escape(command) +
			"</Command>\n      <Arguments>" + xml_escape(arguments) + "</Arguments>\n"
																	  "      <WorkingDirectory>" +
			xml_escape(s.instance_dir.string()) +
			"</WorkingDirectory>\n    </Exec>\n  </Actions>\n";
	out += "</Task>\n";
	return out;
}

} // namespace

ServiceKind host_service_kind() {
#if defined(_WIN32)
	return ServiceKind::TaskScheduler;
#elif defined(__APPLE__)
	return ServiceKind::Launchd;
#else
	return ServiceKind::Systemd;
#endif
}

bool parse_service_kind(const std::string &text, ServiceKind &out) {
	if (text == "systemd")
		out = ServiceKind::Systemd;
	else if (text == "launchd")
		out = ServiceKind::Launchd;
	else if (text == "task")
		out = ServiceKind::TaskScheduler;
	else
		return false;
	return true;
}

std::string render_service(ServiceKind kind, const ServiceSpec &spec) {
	switch (kind) {
		case ServiceKind::Systemd:
			return systemd_unit(spec);
		case ServiceKind::Launchd:
			return launchd_plist(spec);
		case ServiceKind::TaskScheduler:
			return task_xml(spec);
	}
	return {};
}

std::string service_file_name(ServiceKind kind, const std::string &name) {
	switch (kind) {
		case ServiceKind::Systemd:
			return "voxel-browser-" + name + ".service";
		case ServiceKind::Launchd:
			return label(name) + ".plist";
		case ServiceKind::TaskScheduler:
			return "voxel-browser-" + name + ".xml";
	}
	return {};
}

std::string service_install_hint(ServiceKind kind, const ServiceSpec &spec) {
	const std::string file = service_file_name(kind, spec.name);
	switch (kind) {
		case ServiceKind::Systemd:
			return "To run '" + spec.name + "' as a user service (no root needed):\n"
											"  mkdir -p ~/.config/systemd/user\n"
											"  vb server service print " +
					spec.name + " > ~/.config/systemd/user/" + file + "\n"
																	  "  systemctl --user daemon-reload && systemctl --user enable --now " +
					file + "\n"
						   "To keep it running when you are logged out:  loginctl enable-linger $USER\n"
						   "Remove:  systemctl --user disable --now " +
					file + " && rm ~/.config/systemd/user/" + file + "\n";
		case ServiceKind::Launchd:
			return "To run '" + spec.name + "' as a login agent:\n"
											"  vb server service print " +
					spec.name + " > ~/Library/LaunchAgents/" + file + "\n"
																	  "  launchctl bootstrap gui/$(id -u) ~/Library/LaunchAgents/" +
					file + "\n"
						   "Remove:  launchctl bootout gui/$(id -u)/" +
					label(spec.name) + " && rm ~/Library/LaunchAgents/" + file + "\n";
		case ServiceKind::TaskScheduler:
			return "To run '" + spec.name + "' as a task at logon (PowerShell, no administrator needed):\n"
											"  vb server service print " +
					spec.name + " | Out-File -Encoding Unicode " + file + "\n"
																		  "  schtasks /Create /TN \"VoxelBrowser\\" +
					spec.name + "\" /XML " + file + "\n"
													"  schtasks /Run /TN \"VoxelBrowser\\" +
					spec.name + "\"\n"
								"Stop it with `vb server stop " +
					spec.name + "` (ending the task from Task Scheduler\n"
								"terminates the server without saving the world).\n"
								"Remove:  schtasks /Delete /TN \"VoxelBrowser\\" +
					spec.name + "\" /F\n";
	}
	return {};
}

} // namespace vb::cli
