#include "vb/cli/shim.hpp"

#include <system_error>

#if !defined(_WIN32)
#include <sys/stat.h>
#endif

#include "vb/cli/store.hpp"

namespace vb::cli {

namespace fs = std::filesystem;

namespace {

std::string sh_quote(const std::string &s) {
	std::string out = "'";
	for (const char c : s) {
		out += c == '\'' ? std::string("'\\''") : std::string(1, c);
	}
	return out + "'";
}

constexpr const char *kClientName = "voxel_browser";
constexpr const char *kServerName = "voxel_browser_server";

fs::path shim_path(const Layout &layout, const char *name, bool windows) {
	return shim_dir(layout) / (std::string(name) + (windows ? ".cmd" : ""));
}

bool host_is_windows() {
#if defined(_WIN32)
	return true;
#else
	return false;
#endif
}

} // namespace

fs::path shim_dir(const Layout &layout) { return layout.data() / "bin"; }

std::string shim_script(const fs::path &vb_exe, bool server, bool windows) {
	const std::string vb = vb_exe.string();
	if (windows) {
		if (server) {
			return "@echo off\r\nREM Generated by `vb shim install`.\r\nset \"VB_SRV=\"\r\n"
				   "for /f \"usebackq delims=\" %%i in (`\"" +
					vb + "\" which server`) do set \"VB_SRV=%%i\"\r\n"
						 "if not defined VB_SRV exit /b 1\r\n\"%VB_SRV%\" %*\r\n";
		}
		return "@echo off\r\nREM Generated by `vb shim install`.\r\n\"" + vb + "\" launch -- %*\r\n";
	}
	if (server) {
		return "#!/bin/sh\n# Generated by `vb shim install`; re-run it after moving vb.\n"
			   "srv=$(" +
				sh_quote(vb) + " which server) || exit 1\nexec \"$srv\" \"$@\"\n";
	}
	return "#!/bin/sh\n# Generated by `vb shim install`; re-run it after moving vb.\nexec " +
			sh_quote(vb) + " launch -- \"$@\"\n";
}

Status install_shims(const Layout &layout, const fs::path &vb_exe, std::vector<fs::path> &created) {
	if (vb_exe.empty() || !vb_exe.is_absolute()) {
		return { "shims need vb's absolute path" };
	}
	const bool windows = host_is_windows();
	std::error_code ec;
	fs::create_directories(shim_dir(layout), ec);
	if (ec) {
		return { "cannot create " + shim_dir(layout).string() + ": " + ec.message() };
	}
	for (const bool server : { false, true }) {
		const fs::path path = shim_path(layout, server ? kServerName : kClientName, windows);
		if (const Status s = write_text_atomic(path, shim_script(vb_exe, server, windows)); !s) {
			return s;
		}
#if !defined(_WIN32)
		chmod(path.c_str(), 0755);
#endif
		created.push_back(path);
	}
	return {};
}

Status remove_shims(const Layout &layout, std::vector<fs::path> &removed) {
	std::error_code ec;
	for (const char *name : { kClientName, kServerName }) {
		const fs::path path = shim_path(layout, name, host_is_windows());
		if (fs::remove(path, ec)) {
			removed.push_back(path);
		} else if (ec) {
			return { "cannot remove " + path.string() + ": " + ec.message() };
		}
	}
	return {};
}

} // namespace vb::cli
