# cmake/EmbedFiles.cmake
#
# vb_embed_files(<out.cpp> ROOT <dir> GLOBS <pattern>...)
#   Generates a C++ source that holds the bytes of every file matching the glob patterns (relative
#   to ROOT) as `vb::cli::kEmbeddedFiles` (see inc/vb/cli/embedded.hpp), keyed by their
#   ROOT-relative path. Used to bake the `vb pack init` templates and the Lua stubs into `vb`, so
#   it works before any version is installed and can't fail on a missing file. Re-runs CMake when
#   an embedded file changes. No dependency beyond CMake itself.
function(vb_embed_files OUT)
  cmake_parse_arguments(ARG "" "ROOT" "GLOBS" ${ARGN})
  set(_files "")
  foreach(_g IN LISTS ARG_GLOBS)
    file(GLOB_RECURSE _m RELATIVE "${ARG_ROOT}" "${ARG_ROOT}/${_g}")
    list(APPEND _files ${_m})
  endforeach()
  list(REMOVE_DUPLICATES _files)
  list(SORT _files)

  set(_data "")
  set(_table "")
  set(_i 0)
  foreach(_rel IN LISTS _files)
    set(_abs "${ARG_ROOT}/${_rel}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_abs}")
    file(READ "${_abs}" _hex HEX)
    string(LENGTH "${_hex}" _hexlen)
    math(EXPR _size "${_hexlen} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
    if(_size EQUAL 0)
      set(_bytes "0x00,")
    endif()
    string(APPEND _data "static const unsigned char kData${_i}[] = {${_bytes}};\n")
    string(APPEND _table "  { \"${_rel}\", kData${_i}, ${_size} },\n")
    math(EXPR _i "${_i} + 1")
  endforeach()

  set(_text "// Generated by cmake/EmbedFiles.cmake -- do not edit.\n#include \"vb/cli/embedded.hpp\"\n\nnamespace vb::cli {\n\nnamespace {\n${_data}} // namespace\n\nconst EmbeddedFile kEmbeddedFiles[] = {\n${_table}  { nullptr, nullptr, 0 },\n};\nconst std::size_t kEmbeddedFileCount = ${_i};\n\n} // namespace vb::cli\n")
  file(WRITE "${OUT}.tmp" "${_text}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${OUT}.tmp" "${OUT}")
  file(REMOVE "${OUT}.tmp")
endfunction()
