name: Bundle

on:
  workflow_call:

jobs:
  setup_metadata:
    uses: ./.github/workflows/setup_metadata.yml
  
  bundle:
    needs: setup_metadata
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ needs.setup_metadata.outputs.project_name }}
          pattern: ${{ needs.setup_metadata.outputs.project_name }}-*