name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  setup_metadata:
    uses: ./.github/workflows/setup_metadata.yml

  release:
    needs: setup_metadata
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: runner.yml
          name: ${{ needs.setup_metadata.outputs.project_name }} 

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ${{ github.workspace }}/${{ needs.setup_metadata.outputs.project_name }}*